#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.[rotoudjimaye@rotoudjimaye action_hooks]$ cat pre_build
#!/bin/bash
# This is a simple script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.7.0/
export PATH=$PATH:${JAVA_HOME}/bin

export MAVEN_HOME=$OPENSHIFT_DATA_DIR/maven3
export PATH=$PATH:${MAVEN_HOME}/bin
export MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m -Djava.awt.headless=false -Dfile.encoding=UTF-8"

$OPENSHIFT_DATA_DIR/tomcat7/bin/shutdown.sh
cd $OPENSHIFT_REPO_DIR
$OPENSHIFT_REPO_DIR/setup-jython-virtualenv.sh
$MAVEN_HOME/bin/mvn clean package
rm -rf $OPENSHIFT_DATA_DIR/tomcat7/webapps/ROOT
mv target/wanalytics*.war $OPENSHIFT_DATA_DIR/tomcat7/webapps/ROOT.war
$OPENSHIFT_DATA_DIR/tomcat7/bin/startup.sh
